### PR TITLE
Install additional project clients. Fixes #12

### LINKED ISSUE #12: put more pip packages into requirement file
Please put into requirement file for clients(see below). Currently we are not able to deploy hot teamplates. I think a lot of actions are currently missing as clients are not included in requirement file
example: python-PROJECTclient

    nova. Compute API and extensions.
    neutron. Networking API.
    keystone. Identity Service API.
    glance. Image Service API.
    swift. Object Storage API.
    cinder. Block Storage Service API.
    heat. Orchestration API.
    ceilometer. Monitoring/Telemetry API.

### PR DESCRIPTION
**Pull request by LindsayHill**
Install additional OpenStack clients by default (https://wiki.openstack.org/wiki/OpenStackClients)

Fix problem with autogen.py script where actions had a set of integer choices - e.g. IP version `4` or `6`. 

Fixes #12

### CODE REVIEW

**Comment by QualoZe0t** [comment]
hi,
after reinstallation openstack pack autogen.py wasnt executed and actions werent created. I have created manually via autogen.py but i think it should be done automatically.

**Comment by LindsayHill** [comment]
That’s not how it’s supposed to work. There is no mechanism to run code on pack install. If you want new actions created, we should probably create those and add them to here

**Comment by QualoZe0t** [comment]
hi, Yes as you are saying it would be perfect to add here as generating them manually is extra step. For simply usage they should be created and add here

**Comment by LindsayHill** [comment]
@QualoZe0t OK, I have regenerated the action metadata. I have also fixed a problem that was causing these actions to not get auto-generated:

- address.scope.create
- address.scope.list
- ip.availability.list
- subnet.create
- subnet.list

Can you reinstall this branch and check that you're happy with it?

There is a separate issue causing problems with some other actions, such as `network.list`. See https://github.com/StackStorm-Exchange/stackstorm-openstack/issues/6. I don't know exactly what's causing that - it seems to be an issue with the openstack python libraries.

If you're happy with these changes, we'll merge those, and deal with that other problem in #6 separately.

**Pull request merged**
