### PR TITLE
Specify Project per Action

### PR DESCRIPTION
**Pull request by jtopjian**
This commit enables a project name or id to be specified per action.
This allows a user to run different actions against all projects
they belong to ad-hoc.

### CODE REVIEW

**Comment by jtopjian** [comment]
One example of why this is useful is: we add an administrative user to each project in our clouds. Any automation or troubleshooting is done through this user. With this in place, we can do things like:

```shell
$ st2 run openstack.server.list cloud=x project_name=foo
$ st2 run openstack.server.list cloud=x project_name=bar
```

If we tie this into something like ChatOps, it'll just lower the barrier even more for day-to-day troubleshooting.

**Comment by emedvedev** [comment]
That's pretty neat! Could you please push the updated actions and bump the `pack.yaml` version as well?

**Comment by jtopjian** [comment]
@emedvedev I was just in the middle of doing that 😄

**Comment by emedvedev** [comment]
Awesome, merging :) Thanks a lot!

**Comment by jtopjian** [comment]
Thank you!

**Pull request merged**
